# Generated by Django 4.1.13 on 2024-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('catalog', models.CharField(max_length=100)),
                ('public_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('cover', models.ImageField(upload_to='book_covers/')),
                ('sold', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
